# .github/workflows/build_packer_ami.yml
name: Build Packer AMI

on:
  push:
    branches:
      - main
    paths:
      - 'packer.pkr.hcl' # Trigger only if packer files are modified

jobs:
  build-packer-ami:
    name: Build Packer AMI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl -LO https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
          unzip packer_1.7.8_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Initialize Packer
        run: |
          packer init packer.pkr.hcl    

      - name: Build AMI with Packer
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          packer build packer.pkr.hcl
