name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root1234
          MYSQL_DATABASE: projectdatabase_test
          MYSQL_USER: testuser
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Wait for MySQL to be ready
        run: |
          while ! nc -z localhost 3306; do
            sleep 1
          done
      - name: Test MySQL Connection
        run: |
          mysql --host=127.0.0.1 --port=3306 --user=root --password=root1234 -e "SHOW DATABASES;"
      - name: Set up test user
        run: |
          mysql --host=127.0.0.1 --port=3306 --user=root --password=root1234 -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'root';"
          mysql --host=127.0.0.1 --port=3306 --user=root --password=root1234 -e "GRANT ALL PRIVILEGES ON *.* TO 'testuser'@'localhost';"
          mysql --host=127.0.0.1 --port=3306 --user=root --password=root1234 -e "FLUSH PRIVILEGES;"
      - name: Run Sequelize Migrations
        run: npx sequelize-cli db:migrate
        env:
          NODE_ENV: "test"
          DB_HOST: "localhost"
          DB_USERNAME: "testuser"
          DB_PASSWORD: "root1234"
          DB_DATABASE: "projectdatabase_test"

      - name: Run Integration Tests
        run: npx mocha test/**/*.js
        env:
          NODE_ENV: "test"
          DB_HOST: "localhost"
          DB_USERNAME: "testuser"
          DB_PASSWORD: "root1234"
          DB_DATABASE: "projectdatabase_test"