# .github/workflows/packer_ci.yml
name: Packer Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  check-packer-format:
    name: Check Packer Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl -LO https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
          unzip packer_1.7.8_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Debug Current Directory
        run: |
          pwd
          ls -al 

      - name: Run packer fmt 
        run: |
          if ! packer fmt -check packer.pkr.hcl; then
          echo "Packer format incorrect. Please run 'packer fmt' and commit the changes."
          exit 1
          fi
        shell: /usr/bin/bash -e {0}

      - name: Initialize Packer
        run: |
          packer init packer.pkr.hcl

      - name: Validate Packer Configuration
        run: |
          packer validate packer.pkr.hcl
