# .github/workflows/packer_ci.yml
name: Packer Continuous Integration

on:
  pull_request:
    paths:
      - 'packer.pkr.hcl' # Trigger only if packer files are modified

jobs:
  check-packer-format:
    name: Check Packer Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl -LO https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
          unzip packer_1.7.8_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Debug Current Directory
        run: |
          pwd
          ls -al 

      - name: Run packer fmt 
        run: |
          packer fmt packer.pkr.hcl
          # if [ $? -ne 0 ]; then
          #   echo "packer fmt modified the packer template. Please format your packer files."
          #   exit 1
          # fi

      - name: Validate Packer Configuration
        run: |
          packer validate .

  build-packer-ami:
    name: Build Packer AMI
    needs: check-packer-format
    runs-on: ubuntu-latest
    # This ensures the AMI is built only when the PR is merged
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl -LO https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
          unzip packer_1.7.8_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Build AMI with Packer
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          packer build packer.pkr.hcl
